### PR TITLE
Drop UMD bundle from distribution

### PR DESCRIPTION
**Pull request by jonkoops**
This is a draft PR to show what it could look like if we were to drop the UMD bundle (see #190). Specifically, it would allow the elimination of a lot of dependencies (including Rollup), by switching fully to tsup.

### CODE REVIEW

**Review by frederikprijck — COMMENTED** [review]
Thanks, I know it's draft and will keep it open. But I believe dropping UMD and moving away from rollup are two different discussions. I understand the benefit of tsup, and will happily discuss this as well with the team, but as mention do know that we extensively use rollup in all our SDKs, and I dont see any strict need to drop rollup here that justifies the unalignment or the introduction of alignment work in all of our other SDKs.

Additionally, the `npm run dev` command does not work the same anymore, so we will need to bring that back if we were to drop rollup. But again, different conversation as it impacts our general tooling we use with our JavaScript libs/SDKs.

I reached out internally and will get back to this PR.

**Comment by frederikprijck** [comment]
Have had an internal conversation and we might want to see if https://github.com/auth0/jwt-decode/pull/192 would be sufficient before considering a new bundler. Given the size of this library, we might not even need a bundler but the question is if this would cause any issues that TSUP would solve.

Will need to continue investigating this, but wanted to open a draft PR to allow for a conversation.

**Comment by frederikprijck** [comment]
I also dropped UMD on its own here: #193

**Comment by jonkoops** [comment]
Closing this PR as I think #193 and #192 cover this better.

**Pull request closed without merging**
