### PR TITLE
Handle undefined token gracefully

### PR DESCRIPTION
**Pull request by knownasilya**
If there is no token, then this function errors.

### CODE REVIEW

**Comment by knownasilya** [comment]
Ping :+1:

**Comment by dschenkelman** [comment]
Thanks for the PR @knownasilya! I don't think returning is a good idea. I would probably throw an error in this case, as it is an invalid argument. Would you mind making the update to error with a clearly defined message and also document that?

Thanks!

**Comment by knownasilya** [comment]
@dschenkelman is that good what you had in mind?

**Comment by jfromaniello** [comment]
It looks good to me, I released it as `v1.2.0`.

**Comment by knownasilya** [comment]
Thanks.

**Pull request merged**
