### PR TITLE
Avoid using any bundlers but use tsc instead

### PR DESCRIPTION
**Pull request by frederikprijck**
### Description

Given the size of the library, we might want to consider dropping any bundler altogether but move everything into a single file.

According to Are The Types Wrong, this is still outputting correct types:
image

Marked as draft to further investigate.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not the default branch

### CODE REVIEW

**Comment by jonkoops** [comment]
I'll put in a review for this once we merge #193 😄

**Comment by frederikprijck** [comment]
Rebased on top of latest beta.

**Comment by jonkoops** [comment]
Got some review comments, but I think it would be better as a PR, so I will open one up on top of this one.

**Comment by jonkoops** [comment]
I've created #194 with some work that came out of the review. Everything else is looking good to me 👍

**Comment by frederikprijck** [comment]
Thanks @jonkoops !

**Review by ewanharris — APPROVED** [review]

**Pull request merged**
