### PR TITLE
Generate single typings directory (BETA)

### PR DESCRIPTION
**Pull request by cristobal**
Ensure that we only generate a single typings directory, seems that the current `typescript` config as it is now since we output **esm**, **umd** and **cjs** into different directories it generates two additional `typings` directory under `build/esm/typings` and `build/cjs/typings` with the same type definitions i.e.:
Screenshot 2023-08-01 at 19 56 07

With the current changes in this PR we only ensure that we build the type definition declarations files under `build/typings` and not three directories e.g.:
Screenshot 2023-08-01 at 19 57 30

### Before 6.9kb package size and 19 files
Screenshot 2023-08-01 at 20 03 32

### After 6.8kb package size and 13 files
Screenshot 2023-08-01 at 20 04 00

### Savings
The package size in difference is around `0.1kb` it seems not that much, however since this package has about 5.2 millions downloads a week that's about 5.22 GB of bandwidth saved / week from NPM.

### CODE REVIEW

**Comment by cristobal** [comment]
Perhaps this PR should be merged after #183

**Comment by frederikprijck** [comment]
Does #174 change anything here ? Cc @jonkoops ?

**Comment by jonkoops** [comment]
> Does https://github.com/auth0/jwt-decode/pull/174 change anything here ? As i can see it generates the types differently.

Yeah, #174 solves this issue as well. And it goes a step further by bundling the types into a single file (one for ESM, one for CommonJS).  So the directory structure ends up being:

```log
build
├── cjs
│   ├── jwt-decode.cjs
│   └── jwt-decode.d.cts
├── esm
│   ├── jwt-decode.d.ts
│   └── jwt-decode.js
└── jwt-decode.js
```

Having the type definition next to the file (with the same name) like this is considered best practice. This  would also be the default TypeScript compiler behavior, if we weren't using Rollup to bundle it all into a single file.

Furthermore, it is important that both the `"require"` and `"module"` fields have a different files associated with them for the `"types"` field, as per the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/esm-node.html#commonjs-interop):

> It’s important to note that the CommonJS entrypoint and the ES module entrypoint each needs its own declaration file, even if the contents are the same between them. Every declaration file is interpreted either as a CommonJS module or as an ES module, based on its file extension and the `"type"` field of the `package.json`, and this detected module kind must match the module kind that Node will detect for the corresponding JavaScript file for type checking to be correct. Attempting to use a single `.d.ts` file to type both an ES module entrypoint and a CommonJS entrypoint will cause TypeScript to think only one of those entrypoints exists, causing compiler errors for users of the package.

**Comment by cristobal** [comment]
> > Does #174 change anything here ? As i can see it generates the types differently.
> 
> Yeah, #174 solves this issue as well. And it goes a step further by bundling the types into a single file (one for ESM, one for CommonJS). So the directory structure ends up being:
> 
> ```
> build
> ├── cjs
> │   ├── jwt-decode.cjs
> │   └── jwt-decode.d.cts
> ├── esm
> │   ├── jwt-decode.d.ts
> │   └── jwt-decode.js
> └── jwt-decode.js
> ```
> 
> Having the type definition next to the file (with the same name) like this is considered best practice. This would also be the default TypeScript compiler behavior, if we weren't using Rollup to bundle it all into a single file.
> 
> Furthermore, it is important that both the `"require"` and `"module"` fields have a different files associated with them for the `"types"` field, as per the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/esm-node.html#commonjs-interop):
> 
> > It’s important to note that the CommonJS entrypoint and the ES module entrypoint each needs its own declaration file, even if the contents are the same between them. Every declaration file is interpreted either as a CommonJS module or as an ES module, based on its file extension and the `"type"` field of the `package.json`, and this detected module kind must match the module kind that Node will detect for the corresponding JavaScript file for type checking to be correct. Attempting to use a single `.d.ts` file to type both an ES module entrypoint and a CommonJS entrypoint will cause TypeScript to think only one of those entrypoints exists, causing compiler errors for users of the package.

Yes that's correct @jonkoops, closing this PR 👋🏽

**Pull request closed without merging**
