### PR TITLE
Fixed bower.json that wasn't passing bower validation

### PR DESCRIPTION
**Pull request by bladev2**
Latest change set on master needs to be tagged as 1.0.0 so I can use versioning in my application's bower.json correctly :)

You can verify changes work correctly on bower (I set up a temporary package: jwt-decode-test - I'll take this package down once we get this fixed up).

### CODE REVIEW

**Comment by bladev2** [comment]
bump!

**Comment by andrewaustin** [comment]
Bump

**Comment by Rleahy22** [comment]
Bump

**Comment by jfromaniello** [comment]
Merged,  `v1.0.2` should fix this

**Pull request closed without merging**
